### ISSUE TITLE
Workouts CRUD

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/crossfit-wod-api#3]
Implement endpoints for creating, reading, updating, and deleting workouts

**Tasks**

- [ ] create a specific controller, service, and router for our workouts
- [ ] define the endpoint inside the workout router
- [ ] go inside entry point (index.js) and hookup our v1 workout router
